- name: create archieve and fetch
  hosts: all
  tasks:

    - name: create directory
      ansible.builtin.file:
        path: /backup
        state: directory
        mode: '0755'
        owner: student
        group: student

    - name: compress the directory
      community.general.archive:
        path: /etc
        dest: /backup/config.gz
        owner: student
        group: student
        mode: 0660
        format: gz

